447 tank card (#451)

diff --git a/.github/actions/bump-version/action.yml b/.github/actions/bump-version/action.yml
--- a/.github/actions/bump-version/action.yml
+++ b/.github/actions/bump-version/action.yml
@@ -1,33 +1,36 @@
-name: 'Setup node for the action'
-description: 'Bump the npm version and push it on the repo'
+name: 'Setup Maven for the action'
+description: 'Bump the Maven version (stored in properties.revision) and push it on the repo'
 
 inputs:
   version_type:
     description: 'Type of version bump (major, minor, patch)'
     required: true
     type: string
-  MAINTAINER_NAME:
-    description: 'The git user'
-    required: true
-    type: string
-  MAINTAINER_EMAIL:
-    description: 'The git mail'
+  TOKEN:
+    description: 'The git hub token to push the bumped version'
     required: true
     type: string
 
 runs:
   using: 'composite'
   steps:
-    - name: Config git
+    - name: Validate version_type input
       shell: bash
       run: |
-        git config user.name '${{ inputs.MAINTAINER_NAME }}'
-        git config user.email '${{ inputs.MAINTAINER_EMAIL }}'
+        if [[ "${{ inputs.version_type }}" != "major" && "${{ inputs.version_type }}" != "minor" && "${{ inputs.version_type }}" != "patch" ]]; then
+          echo "Invalid version_type: '${{ inputs.version_type }}'. Must be 'major', 'minor', or 'patch'."
+          exit 1
+        fi
+    - name: GIT config
+      shell: bash
+      run: |
+        git config user.name 'github-actions[bot]'
+        git config user.email 'github-actions[bot]@users.noreply.github.com'
     - name: Bump version
       shell: bash
-      run: npm version ${{ inputs.version_type }}
+      run: npm version ${{ inputs.version_type }} -m "Bumped revision version to %s"
     - name: Push version bump commit
       shell: bash
       run: |
         BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
-        git push origin HEAD:$BRANCH --follow-tags
+        git push --follow-tags https://${{ inputs.TOKEN }}@github.com/${{ github.repository }} $BRANCH
